In [132]:
print("Hello world - Huynh Thien Hao")

Hello world - Huynh Thien Hao


In [133]:
import numpy as np
v = np.array([1, 2, 3, 4])
print(v)

[1 2 3 4]


In [134]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A)

[[1 2 3]
 [4 5 6]]


In [135]:
v_col = np.array([
    [1],
    [2],
    [3]
])
print(v_col)

[[1]
 [2]
 [3]]


In [136]:
A = np.zeros((3, 3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [137]:
B = np.ones((3, 3))
print(B)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [138]:
v = np.array([1, 2, 3, 4, 5, 6])
print(v[2])

3


In [139]:
v = np.array([1, 2, 3, 4, 5, 6])
print(v[:2])
print(v[:3])

[1 2]
[1 2 3]


In [140]:
v = np.array([1, 2, 3, 4, 5, 6])
print(v[3:])

[4 5 6]


In [141]:
v = np.array([1, 2, 3, 4, 5, 6])
print(v[::-1])

[6 5 4 3 2 1]


In [142]:
A = np.random.randint(0, 10,(5, 3))
print(A)
print(A[:2, :])

[[0 9 0]
 [9 4 1]
 [3 3 8]
 [8 1 9]
 [8 4 8]]
[[0 9 0]
 [9 4 1]]


In [143]:
A = np.random.randint(0, 10,(5, 3))
print(A)
print(A.ndim)
print(A.size)

[[9 8 9]
 [4 5 6]
 [4 3 7]
 [3 9 3]
 [1 2 7]]
2
15


In [144]:
A = np.random.randint(0, 10,(5, 3))
print(A)
print(A.max())

[[4 9 2]
 [1 4 5]
 [7 2 4]
 [0 6 9]
 [4 1 1]]
9


In [145]:
A = np.random.randint(0, 10,(5, 3))
print(A)
print(A.max(axis=1))
print(A.max(axis=0))

[[8 0 9]
 [7 8 5]
 [7 8 7]
 [0 9 8]
 [6 8 4]]
[9 8 8 9 8]
[8 9 9]


In [146]:
A = np.random.randint(0, 10,(5, 3))
print(A)
print("Trung bình (mean):", np.mean(A))
print("Trung vị (median):", np.median(A))
print("Phương sai (variance):", np.var(A))
print("Độ lệch chuẩn (std):", np.std(A))

p25 = np.percentile(A, 25)
p50 = np.percentile(A, 50)
p75 = np.percentile(A, 75)

print("P25:", p25)
print("P50 (median):", p50)
print("P75:", p75)

[[0 3 0]
 [3 4 5]
 [1 6 1]
 [3 4 0]
 [3 7 5]]
Trung bình (mean): 3.0
Trung vị (median): 3.0
Phương sai (variance): 4.666666666666667
Độ lệch chuẩn (std): 2.160246899469287
P25: 1.0
P50 (median): 3.0
P75: 4.5


In [147]:
A = np.random.randint(0, 10, (5, 3))
print(A)

B = A.reshape((3, 5))
print(B)

v = A.reshape(-1)
print(v)


[[5 9 5]
 [3 3 2]
 [1 9 2]
 [6 2 8]
 [9 7 8]]
[[5 9 5 3 3]
 [2 1 9 2 6]
 [2 8 9 7 8]]
[5 9 5 3 3 2 1 9 2 6 2 8 9 7 8]


In [148]:
A = np.random.randint(0, 10, (5, 3))
print(A)
A_T= A.T
print(A_T)

[[3 5 2]
 [8 5 6]
 [4 5 1]
 [6 1 1]
 [2 3 3]]
[[3 8 4 6 2]
 [5 5 5 1 3]
 [2 6 1 1 3]]


In [149]:
A = np.random.randint(0, 10, (5, 3))
print("Ma trận gốc A \n", A)
B = A.flatten()
B[0] = 100

C = A.ravel()
C[0] = 100

print("Flatten B (copy):", B)
print("Ravel C (view):", C)

Ma trận gốc A 
 [[4 7 6]
 [6 3 6]
 [0 3 9]
 [1 8 5]
 [6 2 5]]
Flatten B (copy): [100   7   6   6   3   6   0   3   9   1   8   5   6   2   5]
Ravel C (view): [100   7   6   6   3   6   0   3   9   1   8   5   6   2   5]


In [150]:
A = np.random.randint(0, 10, (5, 3))
print("Ma trận gốc A \n", A)
rank_A = np.linalg.matrix_rank(A)
print(rank_A)

Ma trận gốc A 
 [[2 5 2]
 [5 6 7]
 [6 2 5]
 [1 6 5]
 [1 9 0]]
3


In [152]:
A = np.random.randint(0, 10, (3, 3))
print("Ma trận gốc A \n", A)
diag = A.diagonal()
print("Đường chéo chính:", diag)

Ma trận gốc A 
 [[1 9 2]
 [9 0 4]
 [6 6 1]]
Đường chéo chính: [1 0 1]


In [153]:
A = np.random.randint(0, 10, (3, 3))
print("Ma trận gốc A \n", A)
diag = A.diagonal(offset=1)
print("Đường chéo chính:", diag)

Ma trận gốc A 
 [[7 2 0]
 [8 1 8]
 [8 9 1]]
Đường chéo chính: [2 8]


In [154]:
A = np.random.randint(0, 10, (3, 3))
print("Ma trận gốc A \n", A)
tr = np.trace(A)
print("Trace của A:", tr)

Ma trận gốc A 
 [[2 0 1]
 [1 2 5]
 [4 0 1]]
Trace của A: 5


In [156]:
a = np.random.randint(0, 10, 3)
print(a)
b = np.random.randint(0, 10, 3)
print(b)
dot1 = np.dot(a, b)

dot2 = a @ b

print("Tích vô hướng (np.dot):", dot1)
print("Tích vô hướng (@):", dot2)

[8 2 4]
[3 1 8]
Tích vô hướng (np.dot): 58
Tích vô hướng (@): 58


In [158]:
a = np.random.randint(0, 10, (3, 6))
print(a)
b = np.random.randint(0, 10, (3, 6))
print(b)
c= a+ b
print(c)
d = np.add(a, b)
print(d)

[[3 1 5 7 6 7]
 [6 4 5 1 7 7]
 [8 3 4 6 3 6]]
[[2 4 4 4 3 1]
 [0 0 6 0 6 6]
 [2 7 3 4 2 5]]
[[ 5  5  9 11  9  8]
 [ 6  4 11  1 13 13]
 [10 10  7 10  5 11]]
[[ 5  5  9 11  9  8]
 [ 6  4 11  1 13 13]
 [10 10  7 10  5 11]]


In [159]:
a = np.random.randint(0, 10, (3, 6))
print(a)
b = np.random.randint(0, 10, (3, 6))
print(b)
c= a * b
print(c)
d = np.multiply(a, b)
print(d)

[[9 7 9 0 2 9]
 [0 8 1 6 3 9]
 [0 8 6 9 0 9]]
[[8 1 4 8 9 1]
 [7 8 6 1 3 1]
 [6 8 5 2 2 4]]
[[72  7 36  0 18  9]
 [ 0 64  6  6  9  9]
 [ 0 64 30 18  0 36]]
[[72  7 36  0 18  9]
 [ 0 64  6  6  9  9]
 [ 0 64 30 18  0 36]]


In [160]:
A = np.random.randint(0, 10, (3, 3))
print("Ma trận gốc A \n", A)
A_inv = np.linalg.inv(A)
print(A_inv)

Ma trận gốc A 
 [[3 1 0]
 [2 5 5]
 [9 9 0]]
[[ 0.5         0.         -0.05555556]
 [-0.5         0.          0.16666667]
 [ 0.3         0.2        -0.14444444]]


In [168]:
x = np.random.rand()
print(x)

mat = np.random.rand(3, 3)
print(mat)

x = np.random.random()
print(x)


0.023569616116172365
[[0.2177701  0.73878315 0.31529082]
 [0.94034477 0.5071503  0.9563571 ]
 [0.25620934 0.33882539 0.81155761]]
0.7896154098120126


In [169]:
arr = np.random.randint(0, 10, 5)
print(arr)

[9 2 8 7 7]


In [172]:
a = np.random.randint(0, 10, 3)
print(a)
b = np.random.randint(0, 10, 3)
print(b)
result = np.inner(a, b)
print(result)

[9 0 3]
[6 0 3]
63


In [173]:
v = np.array([1, -2, 3, -4])

norm_L1 = np.linalg.norm(v, ord=1)
print("Norm L1 của v:", norm_L1)

Norm L1 của v: 10.0


In [174]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

C = A.dot(B)

print("A.dot(B) =\n", C)
print("Phần tử hàng đầu cột đầu:", C[0,0])

A.dot(B) =
 [[19 22]
 [43 50]]
Phần tử hàng đầu cột đầu: 19


In [180]:
np.random.seed(0)
arr = np.random.randint(0, 10, 5)
print(arr)

[5 0 3 3 7]


In [182]:
np.random.seed(0)
#np.random.normal(loc=0.0, scale=1.0, size=3) tạo số thực ngẫu nhiên theo phân phối chuẩn
arr = np.random.normal(0.0, 1.0, 3)
print(arr)

[1.76405235 0.40015721 0.97873798]


In [183]:
A = np.random.randint(0, 10, (3, 3))
trace_A = np.sum(A.diagonal())
print("Trace của A:", trace_A)


Trace của A: 21
