In [9]:
import numpy as np

# DATA
X = np.array([1.0,2.5,4.0,5.5,7.0,8.0])
y = np.array([0,0,1,1,2,2])  # labels 0..2

def one_hot(y, K=3):
    out = np.zeros((len(y), K))
    out[np.arange(len(y)), y] = 1
    return out

Y = one_hot(y)

# PARAMETERS
W = np.zeros((3,1))   # (K, D)
b = np.zeros((3,1))
eta = 0.2
epochs = 2

for ep in range(epochs):
    for i in range(len(X)):
        x = np.array([[X[i]]])      # shape (1,1)
        t = Y[i].reshape(3,1)       # target vector

        # forward
        z = W @ x + b
        y_hat = np.exp(z) / np.sum(np.exp(z))

        # gradient
        grad = (y_hat - t)

        # update
        W -= eta * grad * x
        b -= eta * grad

print("W =", W)
print("b =", b)


W = [[-0.43681602]
 [-0.64863812]
 [ 1.08545414]]
b = [[ 0.25024827]
 [-0.00039746]
 [-0.24985081]]


In [10]:
import numpy as np

X = np.array([1.0,2.5,4.0,5.5,7.0,8.0]).reshape(-1,1)
y = np.array([0,0,1,1,2,2])

def one_hot(y, K=3):
    out = np.zeros((len(y), K))
    out[np.arange(len(y)), y] = 1
    return out

Y = one_hot(y)

W = np.zeros((3,1))
b = np.zeros((3,1))

eta = 0.2
epochs = 2

for ep in range(epochs):
    z = X @ W.T + b.T            # (6,3)
    y_hat = np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)

    grad_W = ((y_hat - Y).T @ X) / len(X)
    grad_b = np.mean((y_hat - Y), axis=0, keepdims=True).T

    W -= eta * grad_W
    b -= eta * grad_b

print("W =", W)
print("b =", b)


W = [[-0.15618969]
 [ 0.10606362]
 [ 0.05012607]]
b = [[ 0.0414144 ]
 [ 0.01466559]
 [-0.05607999]]


In [11]:
import numpy as np

# giả sử bạn có X đa biến
# ví dụ X có 6 mẫu, 3 features
# X shape: (N, D)
# y có 3 lớp (0,1,2)

# DATA DEMO (thay bằng dữ liệu thật của bạn)
X = np.array([
    [1.0, 2.0, 0.5],
    [2.5, 0.4, 1.5],
    [4.0, 1.0, 2.0],
    [5.5, 3.0, 1.2],
    [7.0, 2.5, 2.1],
    [8.0, 1.1, 0.3]
])

y = np.array([0,0,1,1,2,2])

# SHAPES
N, D = X.shape
K = 3     # số lớp

def one_hot(y, K):
    out = np.zeros((len(y), K))
    out[np.arange(len(y)), y] = 1
    return out

Y = one_hot(y, K)

# PARAMETERS
W = np.zeros((K, D))   # W shape (K, D)
b = np.zeros((K,1))    # b shape (K,1)
eta = 0.2
epochs = 2

for ep in range(epochs):
    for i in range(N):
        x = X[i].reshape(D,1)   # (D,1)
        t = Y[i].reshape(K,1)   # (K,1)

        # forward
        z = W @ x + b
        y_hat = np.exp(z)/np.sum(np.exp(z))

        # gradient
        grad = y_hat - t

        # update
        W -= eta * grad @ x.T
        b -= eta * grad

print("W =\n", W)
print("b =\n", b)


W =
 [[-0.5952678   0.24944393 -0.1393492 ]
 [-0.54003668 -0.29300792  0.03602987]
 [ 1.13530448  0.04356398  0.10331933]]
b =
 [[ 0.21355566]
 [ 0.03739928]
 [-0.25095494]]


In [12]:
import numpy as np

X = np.array([
    [1.0, 2.0, 0.5],
    [2.5, 0.4, 1.5],
    [4.0, 1.0, 2.0],
    [5.5, 3.0, 1.2],
    [7.0, 2.5, 2.1],
    [8.0, 1.1, 0.3]
])

y = np.array([0,0,1,1,2,2])

N, D = X.shape
K = 3

def one_hot(y, K):
    out = np.zeros((len(y), K))
    out[np.arange(len(y)), y] = 1
    return out

Y = one_hot(y, K)

W = np.zeros((K, D))
b = np.zeros((K,1))

eta = 0.2
epochs = 2

for ep in range(epochs):
    z = X @ W.T + b.T                 # (N, K)
    y_hat = np.exp(z)/np.sum(np.exp(z), axis=1, keepdims=True)

    grad_W = ((y_hat - Y).T @ X) / N
    grad_b = np.mean((y_hat - Y), axis=0, keepdims=True).T

    W -= eta * grad_W
    b -= eta * grad_b

print("W =\n", W)
print("b =\n", b)


W =
 [[-0.14951856  0.01379095  0.02149133]
 [ 0.09458493  0.06659795  0.05898269]
 [ 0.05493363 -0.0803889  -0.08047402]]
b =
 [[ 0.04332663]
 [ 0.01196418]
 [-0.05529081]]
